# Generated by Django 5.0.6 on 2025-05-26 01:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id_categoria', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id_cliente', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('email', models.TextField()),
                ('telefono', models.CharField(max_length=9)),
                ('direccion', models.CharField(max_length=100)),
                ('dni', models.CharField(max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='Entrada',
            fields=[
                ('id_entrada', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_entrada', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id_marca', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='PedidoProveedor',
            fields=[
                ('id_pedido_proveedor', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_pedido', models.DateTimeField()),
                ('estado', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id_proveedor', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('email', models.TextField()),
                ('telefono', models.CharField(max_length=9)),
                ('direccion', models.CharField(blank=True, max_length=100, null=True)),
                ('dni', models.CharField(max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id_rol', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Talla',
            fields=[
                ('id_talla', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_talla', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id_user', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('email', models.TextField()),
                ('password', models.CharField(max_length=255)),
                ('token', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Prenda',
            fields=[
                ('id_prenda', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=255)),
                ('color', models.CharField(max_length=255)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=18)),
                ('stock', models.IntegerField()),
                ('id_categoria', models.ForeignKey(db_column='id_categoria', on_delete=django.db.models.deletion.CASCADE, related_name='prendas', to='api.categoria')),
                ('id_marca', models.ForeignKey(db_column='id_marca', on_delete=django.db.models.deletion.CASCADE, related_name='prendas', to='api.marca')),
                ('id_proveedor', models.ForeignKey(db_column='id_proveedor', on_delete=django.db.models.deletion.CASCADE, related_name='prendas', to='api.proveedor')),
                ('id_talla', models.ForeignKey(db_column='id_talla', on_delete=django.db.models.deletion.CASCADE, related_name='prendas', to='api.talla')),
            ],
        ),
        migrations.CreateModel(
            name='DetallePedido',
            fields=[
                ('id_detalle_pedido', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField()),
                ('id_pedido_proveedor', models.ForeignKey(db_column='id_pedido_proveedor', on_delete=django.db.models.deletion.CASCADE, related_name='detalles_pedidos', to='api.pedidoproveedor')),
                ('id_prenda', models.ForeignKey(db_column='id_prenda', on_delete=django.db.models.deletion.CASCADE, related_name='detalles_pedidos', to='api.prenda')),
            ],
        ),
        migrations.CreateModel(
            name='DetalleEntrada',
            fields=[
                ('id_detalle_entrada', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField()),
                ('precio_compra', models.DecimalField(decimal_places=2, max_digits=18)),
                ('id_entrada', models.ForeignKey(db_column='id_entrada', on_delete=django.db.models.deletion.CASCADE, related_name='detalles_entradas', to='api.entrada')),
                ('id_prenda', models.ForeignKey(db_column='id_prenda', on_delete=django.db.models.deletion.CASCADE, related_name='detalles_entradas', to='api.prenda')),
            ],
        ),
        migrations.AddField(
            model_name='pedidoproveedor',
            name='id_proveedor',
            field=models.ForeignKey(db_column='id_proveedor', on_delete=django.db.models.deletion.CASCADE, related_name='pedidos_proveedor', to='api.proveedor'),
        ),
        migrations.AddField(
            model_name='entrada',
            name='id_proveedor',
            field=models.ForeignKey(db_column='id_proveedor', on_delete=django.db.models.deletion.CASCADE, related_name='entradas', to='api.proveedor'),
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id_empleado', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('email', models.TextField()),
                ('telefono', models.CharField(max_length=9)),
                ('direccion', models.CharField(max_length=100)),
                ('dni', models.CharField(max_length=8)),
                ('imagen_perfil', models.TextField(blank=True, null=True)),
                ('imagen_perfil_url', models.TextField(blank=True, null=True)),
                ('id_rol', models.ForeignKey(db_column='id_rol', on_delete=django.db.models.deletion.CASCADE, related_name='empleados', to='api.rol')),
                ('id_user', models.OneToOneField(db_column='id_user', on_delete=django.db.models.deletion.CASCADE, related_name='empleado', to='api.user')),
            ],
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id_venta', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_venta', models.DateTimeField()),
                ('direccion_venta', models.CharField(max_length=100)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('metodo_pago', models.CharField(max_length=50)),
                ('id_cliente', models.ForeignKey(db_column='id_cliente', on_delete=django.db.models.deletion.CASCADE, related_name='ventas', to='api.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='DetalleVenta',
            fields=[
                ('id_detalle_venta', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField()),
                ('precio_venta_real', models.DecimalField(decimal_places=2, max_digits=18)),
                ('id_prenda', models.ForeignKey(db_column='id_prenda', on_delete=django.db.models.deletion.CASCADE, related_name='detalles_ventas', to='api.prenda')),
                ('id_venta', models.ForeignKey(db_column='id_venta', on_delete=django.db.models.deletion.CASCADE, related_name='detalles_ventas', to='api.venta')),
            ],
        ),
    ]
