# Generated by Django 5.2 on 2025-05-26 03:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReclamacionPedido',
            fields=[
                ('id_reclamacion_pedido', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_reclamacion', models.DateTimeField()),
                ('motivo', models.CharField(max_length=255)),
                ('id_cliente', models.ForeignKey(db_column='id_cliente', on_delete=django.db.models.deletion.CASCADE, related_name='reclamaciones_pedidos', to='api.cliente')),
                ('id_pedido_proveedor', models.ForeignKey(db_column='id_pedido_proveedor', on_delete=django.db.models.deletion.CASCADE, related_name='reclamaciones_pedidos', to='api.pedidoproveedor')),
            ],
        ),
    ]
